# Uncomment the next line to define a global platform for your project
platform :ios, '13.4'

target 'Client VK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Client VK
	pod 'RealmSwift'
	pod 'SwiftKeychainWrapper'

end
